### ISSUE TITLE
8 instances of stereo MP3 audio in training dataset of CommonVoice/en_1932h_2020-06-22

### ISSUE THREAD

**Issue by antimora** [mozilla/CorporaCreator#109]
Whiling running some training tests, I have discovered the training dataset contains stereo mp3 files. Here are the instances:

```

Ref: common_voice_en_21795381
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21795381.mp3
Sample Rate:  44100
Channels: 2


Ref: common_voice_en_21795384
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21795384.mp3
Sample Rate:  44100
Channels: 2


Ref: common_voice_en_21795388
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21795388.mp3
Sample Rate:  44100
Channels: 2

Ref: common_voice_en_21802148
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21802148.mp3
Sample Rate:  44100
Channels: 2

Ref: common_voice_en_21849614
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21849614.mp3
Sample Rate:  44100
Channels: 2

Ref: common_voice_en_21849647
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21849647.mp3
Sample Rate:  44100
Channels: 2

Ref: common_voice_en_21849710
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21849710.mp3
Sample Rate:  44100
Channels: 2

Ref: common_voice_en_21849740
Audio Path: CommonVoice/en_1932h_2020-06-22/extracted/cv-corpus-5-2020-06-22/en/clips/common_voice_en_21849740.mp3
Sample Rate:  44100
Channels: 2
```

On a related note. I have noticed the MP3 are encoded in 44100 and 48000 sample rates. Is this right? Shouldn't the audio files be encoded consistantly?

**Comment by phirework** [comment]
Thank you for this report! The Corpora Creator actually doesn't have anything to do with the audio of the dataset, that happens on the Common Voice platform, and this bug is most likely an artifact of our web app. Can I get you to refile this issue in our datasets repo? https://github.com/Common-Voice/cv-dataset Unfortunately I can't automatically transfer this issue because the two repos belong to different organizations, sorry about that. 

Can you also clarify whether this is a blocking concern (i.e. your system straight up cannot work with stereo audio) or merely an odd inconsistency?

**Comment by antimora** [comment]
@phirework I have refiled in this project: https://github.com/Common-Voice/common-voice-bundler/issues/9 instead of cv-dataset, which is more concerned about metadata than MP3 files.
