### ISSUE TITLE
Fix stereo files to mono

### ISSUE THREAD

**Issue by Mte90** [mozilla/CorporaCreator#110]
As I know DeepSpeech crashes if find stereo files:
![photo_2020-07-31_19-57-52](https://user-images.githubusercontent.com/403283/89193595-815f1100-d5a6-11ea-8b11-92672e5c6fb7.jpg)

The files in the Italian CV datasets are:
```
cv-corpus-5.1-2020-06-22/it/clips/common_voice_it_21431109.mp3 
cv-corpus-5.1-2020-06-22/it/clips/common_voice_it_21431655.mp3
```

It is possible to fix this 2 files and not generate anymore dataset with that problem? or we need to implement a check for any file on model generation that slowdown a lot the process.

**Comment by Mte90** [comment]
https://github.com/MozillaItalia/DeepSpeech-Italian-Model/commit/7759dbab602982b6eac33ef6b1a4c8e319ffe62a we fixed right now with convert this files in mono

**Comment by phirework** [comment]
Hey @Mte90, thanks for filing this. The Corpora Creator actually doesn't have anything to do with the audio of the dataset, that happens on the Common Voice platform, and this bug is most likely an artifact of our web app. Can I get you to refile this issue in our datasets repo? https://github.com/Common-Voice/cv-dataset Unfortunately I can't automatically transfer this issue because the two repos belong to different organizations, sorry about that.

**Comment by Mte90** [comment]
So this generator don't check if the files are mono or not before package it?
I will open also there the ticket.
